#!/usr/bin/env python3
"""Generate osd/osd_font.h: antialiased ASCII bitmap atlases (32..126) for
the OSD renderer. Two sizes:
  normal 16x32 (24 pt)  - primary telemetry text
  small   8x16 (12 pt)  - secondary info (frame counter, temps, subtitles)
"""
import os
from PIL import Image, ImageFont, ImageDraw

FIRST, LAST = 32, 126
SIZES = [("FONT_W", "FONT_H", "FONT_ATLAS", 16, 32, 24),
         ("FONT_W_SMALL", "FONT_H_SMALL", "FONT_ATLAS_SMALL", 8, 16, 12)]

SEARCH = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf",
]

def find_font():
    for p in SEARCH:
        if os.path.exists(p):
            return p
    raise SystemExit("no monospace ttf font found in: %s" % SEARCH)

def render(path, size, cw, ch):
    font = ImageFont.truetype(path, size)
    atlas = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cw, ch), 0)
        d = ImageDraw.Draw(img)
        d.text((cw // 2, ch // 2 + 1), chr(code), font=font, anchor="mm", fill=255)
        atlas.append(list(img.getdata()))
    return atlas

path = find_font()
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "osd", "osd_font.h"), "w") as f:
    f.write("/* Auto-generated by gen_font.py - AA atlases, ASCII 32..126. Do not edit. */\n")
    f.write("#pragma once\n")
    f.write("#define FONT_FIRST %d\n#define FONT_COUNT %d\n" % (FIRST, LAST - FIRST + 1))
    for wname, hname, aname, cw, ch, pt in SIZES:
        f.write("#define %s %d\n#define %s %d\n" % (wname, cw, hname, ch))
    for wname, hname, aname, cw, ch, pt in SIZES:
        atlas = render(path, pt, cw, ch)
        f.write("static const unsigned char %s[FONT_COUNT][%d * %d] = {\n"
                % (aname, ch, cw))
        for glyph in atlas:
            f.write("{" + ",".join(str(v) for v in glyph) + "},\n")
        f.write("};\n")

print("font source:", path, "-> osd/osd_font.h")
