#!/usr/bin/env python3
"""Generate osd_font.h : 16x32 antialiased ASCII bitmap atlas (32..126) for the OSD renderer."""
import os
from PIL import Image, ImageFont, ImageDraw

CW, CH, FIRST, LAST = 16, 32, 32, 126

SEARCH = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf",
]

def find_font():
    for p in SEARCH:
        if os.path.exists(p):
            return p
    raise SystemExit("no monospace ttf font found in: %s" % SEARCH)

path = find_font()
font = ImageFont.truetype(path, 24)

atlas = []
for ch in range(FIRST, LAST + 1):
    img = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(img)
    d.text((CW // 2, CH // 2 + 1), chr(ch), font=font, anchor="mm", fill=255)
    atlas.append(list(img.getdata()))

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "osd_font.h"), "w") as f:
    f.write("/* Auto-generated by gen_font.py - 16x32 AA atlas, ASCII 32..126. Do not edit. */\n")
    f.write("#pragma once\n")
    f.write("#define FONT_W %d\n#define FONT_H %d\n#define FONT_FIRST %d\n#define FONT_COUNT %d\n"
            % (CW, CH, FIRST, LAST - FIRST + 1))
    f.write("static const unsigned char FONT_ATLAS[FONT_COUNT][FONT_H * FONT_W] = {\n")
    for glyph in atlas:
        f.write("{" + ",".join(str(v) for v in glyph) + "},\n")
    f.write("};\n")

print("font source:", path, "-> osd_font.h")
